name: eye_diagnostic_system
description: An Eye Diagnostic System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
#  flutter_svg: ^0.18.1
  flutter_svg: ^0.20.0-nullsafety.3
  google_maps_flutter: ^0.5.30
  geolocator: ^5.3.0
  google_maps_webservice: ^0.0.16
  http: ^0.12.0+2
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^6.0.13
  connectivity: ^0.4.8+2
  rflutter_alert: ^1.0.2
  modal_progress_hud: ^0.1.3
  firebase_core: ^0.5.0
  webview_flutter: ^0.3.20
  url_launcher: ^4.0.2
  shared_preferences: ^0.5.6+3
  flutter_speed_dial: ^1.2.5
  material_design_icons_flutter: ^2.7.94
  auto_size_text: ^2.1.0
  google_sign_in: ^4.5.3
  tcard: ^1.2.2
  group_radio_button: ^1.0.1
  flutter_dialogflow: ^0.1.3
  intl: ^0.16.1
  bubble: ^1.1.9+1
  screen: ^0.0.5
  speech_to_text: ^2.5.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2+1
  flutter_tts: ^1.2.7
  font_awesome_flutter: ^8.8.1
  sqflite: ^1.3.1+1
  path_provider: ^1.6.14
  flare_splash_screen: ^3.0.1
  syncfusion_flutter_charts: ^18.4.30
  camera: ^0.6.0
  path: ^1.7.0
  image_picker: ^0.6.7+22
  dio: ^3.0.10
  flutter_map: ^0.11.0
  sliding_up_panel: ^1.0.2
  cached_network_image: ^2.0.0
  flutter_rating_bar: ^4.0.0
  flutter_local_notifications: ^4.0.1+2
  rxdart: ^0.23.1
  timezone: ^0.6.1
  flutter_slidable: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/places/
    - assets/images/contrast/
    - assets/logos/
    - assets/images/svgs/
    - assets/images/colorblindness/
    - assets/images/rules/
    - assets/json/service.json
    - assets/json/eye_facts.json
    - assets/images/near_vision/
    - assets/images/rules/
    - assets/images/vision_testing/
    - assets/images/visual_acuity/snellens/
    - assets/images/on_boarding/
    - assets/images/dashboard/
    - assets/animations/eyeseesplash.flr
    - assets/json/hospitals/hospitals-v1-json.json
    - assets/images/vision_testing/main_icons/
    - assets/images/vision_testing/duo-chrome tests/
    - assets/images/vision_testing/instructions_icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

